[programs.localnet]
auction_factory = "EBTuRco9ht6f2R27RGbKHVcoz31n3fMDHFSEvecibZDU"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/jacobshiohira/.config/solana/id.json"

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts"